version: 2.1

# # Check out orbs later
# orbs:
#   python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.4
    # executor: python/default
    steps:
      - checkout
      - run:
          command: python -m pip install pytest pytest-html -r requirements.txt --user
          name: Install-deps
      - run:
          command: chmod -R 755 convert_source/tests
          name: Change file permissions
      - run:
        command: cd convert_source/tests
        name: Change working directory
      - run:
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html convert_source/tests/
          name: Run unit tests
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  main:
    jobs:
      - build-and-test