# Example configuration file

# Heurestic search terms for each modality
modality_search:
    # Anatomical scans
    anat:
        T1w: 
            - T1
            - T1w
        T2w: 
            - T2
            - T2w

    # Functional scans
    func:
        # BOLD contrast
        bold: 
            rest: 
                - rsfMR
                - rest

    # Diffusion Weighted Scans
    dwi:
        dwi: 
            - diffusion


# Metadata Settings
metadata:
    common:
        Manufacturer: Philips
        ManufacturersModelName: Ingenia
        MagneticFieldStrength: 3
        InstitutionName: Cincinnati Children's Hospital Medical Center
    func:
        rest:
            ParallelAcquisitionTechnique: SENSE # GRAPPA, for the general term
            PhaseEncodingDirection: 'j'
            MultibandAccelerationFactor: 6
            TaskName: Resting State
            dir: PA
            NumberOfVolumesDiscardedByScanner: 4

# Exclusion List (these filenames are not converted)
exclude: 
    - SURVEY
    - Reg
    - DEFAULT
    - ScreenCapture


